<?xml version="1.0" encoding="US-ASCII" standalone="yes"?>
<!DOCTYPE stationlist [
<!ELEMENT stationlist (station+)>
<!ATTLIST stationlist
  created	CDATA	#REQUIRED
>

<!ELEMENT station (comp+)>
<!ATTLIST station
  code		CDATA 			#REQUIRED
  name		CDATA 			#REQUIRED
  insttype	CDATA 			#REQUIRED
  lat		CDATA 			#REQUIRED
  lon		CDATA 			#REQUIRED
  source	(SCSN|CGS|NSMP) 	'SCSN'
  netid		CDATA			#REQUIRED
  commtype	(DIG|ANA) 		'DIG'
  dist          CDATA                   '10.0'
  loc		CDATA			''
>

<!ELEMENT comp (acc,vel,psa*)>
<!ATTLIST comp
  name          CDATA  #REQUIRED
  originalname  CDATA  #IMPLIED
>

<!ELEMENT acc EMPTY>
<!ELEMENT vel EMPTY>
<!ELEMENT psa03 EMPTY>
<!ELEMENT psa10 EMPTY>
<!ELEMENT psa30 EMPTY>
<!ATTLIST acc
  value  CDATA         #REQUIRED
  flag   CDATA        ''
>
<!ATTLIST vel
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa03
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa10
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa30
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
]>
<stationlist created="1224096519">
<station code="91042" name="ZIP Code 91042 (Intensity VII, 38 responses)" insttype="USGS (Did You Feel It?)" lat="34.282604" lon="-118.237943" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.4">
<comp name="Intensity Questionnaire">
<acc value="30.4608" />
<vel value="28.5319" />
</comp>
</station>
<station code="92584" name="ZIP Code 92584 (Intensity IV, 4 responses)" insttype="USGS (Did You Feel It?)" lat="33.657910" lon="-117.178161" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="3.6">
<comp name="Intensity Questionnaire">
<acc value="2.7893" />
<vel value="2.2921" />
</comp>
</station>
<station code="90302" name="ZIP Code 90302 (Intensity VII, 4 responses)" insttype="USGS (Did You Feel It?)" lat="33.974611" lon="-118.35517" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.2">
<comp name="Intensity Questionnaire">
<acc value="26.8594" />
<vel value="24.9859" />
</comp>
</station>
<station code="92122" name="ZIP Code 92122 (Intensity IV, 23 responses)" insttype="USGS (Did You Feel It?)" lat="32.856662" lon="-117.210068" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="4.1">
<comp name="Intensity Questionnaire">
<acc value="3.8203" />
<vel value="3.1939" />
</comp>
</station>
<station code="91350" name="ZIP Code 91350 (Intensity VIII, 72 responses)" insttype="USGS (Did You Feel It?)" lat="34.424976" lon="-118.515374" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.8">
<comp name="Intensity Questionnaire">
<acc value="39.1769" />
<vel value="37.2053" />
</comp>
</station>
<station code="92057" name="ZIP Code 92057 (Intensity IV, 6 responses)" insttype="USGS (Did You Feel It?)" lat="33.252223" lon="-117.290161" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="4.4">
<comp name="Intensity Questionnaire">
<acc value="4.6139" />
<vel value="3.8974" />
</comp>
</station>
<station code="92019" name="ZIP Code 92019 (Intensity IV, 4 responses)" insttype="USGS (Did You Feel It?)" lat="32.780333" lon="-116.879818" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="3.5">
<comp name="Intensity Questionnaire">
<acc value="2.6192" />
<vel value="2.1449" />
</comp>
</station>
<station code="92101" name="ZIP Code 92101 (Intensity IV, 10 responses)" insttype="USGS (Did You Feel It?)" lat="32.723295" lon="-117.16933" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="4.2">
<comp name="Intensity Questionnaire">
<acc value="4.0684" />
<vel value="3.4130" />
</comp>
</station>
<station code="90008" name="ZIP Code 90008 (Intensity VIII, 8 responses)" insttype="USGS (Did You Feel It?)" lat="34.009030" lon="-118.348145" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.6">
<comp name="Intensity Questionnaire">
<acc value="34.5450" />
<vel value="32.5813" />
</comp>
</station>
<station code="92103" name="ZIP Code 92103 (Intensity V, 16 responses)" insttype="USGS (Did You Feel It?)" lat="32.747328" lon="-117.166835" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.0">
<comp name="Intensity Questionnaire">
<acc value="6.7298" />
<vel value="5.8035" />
</comp>
</station>
<station code="92243" name="ZIP Code 92243 (Intensity III, 4 responses)" insttype="USGS (Did You Feel It?)" lat="32.774777" lon="-115.598948" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="3.0">
<comp name="Intensity Questionnaire">
<acc value="1.9123" />
<vel value="1.5393" />
</comp>
</station>
<station code="93013" name="ZIP Code 93013 (Intensity VI, 11 responses)" insttype="USGS (Did You Feel It?)" lat="34.414751" lon="-119.515492" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.8">
<comp name="Intensity Questionnaire">
<acc value="11.1322" />
<vel value="9.8682" />
</comp>
</station>
<station code="91910" name="ZIP Code 91910 (Intensity IV, 14 responses)" insttype="USGS (Did You Feel It?)" lat="32.637922" lon="-117.055419" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="4.3">
<comp name="Intensity Questionnaire">
<acc value="4.3326" />
<vel value="3.6472" />
</comp>
</station>
<station code="90066" name="ZIP Code 90066 (Intensity VII, 76 responses)" insttype="USGS (Did You Feel It?)" lat="33.999244" lon="-118.429728" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.3">
<comp name="Intensity Questionnaire">
<acc value="28.6035" />
<vel value="26.7001" />
</comp>
</station>
<station code="91302" name="ZIP Code 91302 (Intensity VIII, 35 responses)" insttype="USGS (Did You Feel It?)" lat="34.123996" lon="-118.672365" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.8">
<comp name="Intensity Questionnaire">
<acc value="39.1769" />
<vel value="37.2053" />
</comp>
</station>
<station code="91606" name="ZIP Code 91606 (Intensity VIII, 42 responses)" insttype="USGS (Did You Feel It?)" lat="34.186831" lon="-118.389004" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.7">
<comp name="Intensity Questionnaire">
<acc value="36.7882" />
<vel value="34.8166" />
</comp>
</station>
<station code="91360" name="ZIP Code 91360 (Intensity VII, 83 responses)" insttype="USGS (Did You Feel It?)" lat="34.214054" lon="-118.880805" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.0">
<comp name="Intensity Questionnaire">
<acc value="23.6838" />
<vel value="21.8805" />
</comp>
</station>
<station code="90272" name="ZIP Code 90272 (Intensity VII, 30 responses)" insttype="USGS (Did You Feel It?)" lat="34.079765" lon="-118.544388" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.8">
<comp name="Intensity Questionnaire">
<acc value="20.8836" />
<vel value="19.1611" />
</comp>
</station>
<station code="91205" name="ZIP Code 91205 (Intensity VII, 17 responses)" insttype="USGS (Did You Feel It?)" lat="34.136614" lon="-118.243507" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.8">
<comp name="Intensity Questionnaire">
<acc value="20.8836" />
<vel value="19.1611" />
</comp>
</station>
<station code="90650" name="ZIP Code 90650 (Intensity VI, 20 responses)" insttype="USGS (Did You Feel It?)" lat="33.906961" lon="-118.082812" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.9">
<comp name="Intensity Questionnaire">
<acc value="11.8551" />
<vel value="10.5452" />
</comp>
</station>
<station code="92807" name="ZIP Code 92807 (Intensity VI, 20 responses)" insttype="USGS (Did You Feel It?)" lat="33.849130" lon="-117.788484" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.6">
<comp name="Intensity Questionnaire">
<acc value="9.8161" />
<vel value="8.6417" />
</comp>
</station>
<station code="90260" name="ZIP Code 90260 (Intensity VI, 9 responses)" insttype="USGS (Did You Feel It?)" lat="33.889224" lon="-118.35291" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.2">
<comp name="Intensity Questionnaire">
<acc value="14.3177" />
<vel value="12.8680" />
</comp>
</station>
<station code="91107" name="ZIP Code 91107 (Intensity VI, 86 responses)" insttype="USGS (Did You Feel It?)" lat="34.158928" lon="-118.087257" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.9">
<comp name="Intensity Questionnaire">
<acc value="11.8551" />
<vel value="10.5452" />
</comp>
</station>
<station code="92648" name="ZIP Code 92648 (Intensity VI, 26 responses)" insttype="USGS (Did You Feel It?)" lat="33.682443" lon="-118.012724" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.8">
<comp name="Intensity Questionnaire">
<acc value="11.1322" />
<vel value="9.8682" />
</comp>
</station>
<station code="92649" name="ZIP Code 92649 (Intensity VI, 22 responses)" insttype="USGS (Did You Feel It?)" lat="33.721145" lon="-118.044453" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.2">
<comp name="Intensity Questionnaire">
<acc value="14.3177" />
<vel value="12.8680" />
</comp>
</station>
<station code="92504" name="ZIP Code 92504 (Intensity VI, 14 responses)" insttype="USGS (Did You Feel It?)" lat="33.906878" lon="-117.398719" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.1">
<comp name="Intensity Questionnaire">
<acc value="13.4447" />
<vel value="12.0418" />
</comp>
</station>
<station code="90732" name="ZIP Code 90732 (Intensity VII, 17 responses)" insttype="USGS (Did You Feel It?)" lat="33.733678" lon="-118.313017" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.5">
<comp name="Intensity Questionnaire">
<acc value="17.2918" />
<vel value="15.7024" />
</comp>
</station>
<station code="92673" name="ZIP Code 92673 (Intensity VI, 4 responses)" insttype="USGS (Did You Feel It?)" lat="33.465010" lon="-117.612945" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.6">
<comp name="Intensity Questionnaire">
<acc value="9.8161" />
<vel value="8.6417" />
</comp>
</station>
<station code="93003" name="ZIP Code 93003 (Intensity VI, 61 responses)" insttype="USGS (Did You Feel It?)" lat="34.278967" lon="-119.218586" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.1">
<comp name="Intensity Questionnaire">
<acc value="13.4447" />
<vel value="12.0418" />
</comp>
</station>
<station code="91202" name="ZIP Code 91202 (Intensity VII, 24 responses)" insttype="USGS (Did You Feel It?)" lat="34.168289" lon="-118.267874" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.2">
<comp name="Intensity Questionnaire">
<acc value="26.8594" />
<vel value="24.9859" />
</comp>
</station>
<station code="92868" name="ZIP Code 92868 (Intensity VI, 9 responses)" insttype="USGS (Did You Feel It?)" lat="33.787770" lon="-117.876462" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.4">
<comp name="Intensity Questionnaire">
<acc value="16.2374" />
<vel value="14.6942" />
</comp>
</station>
<station code="95064" name="ZIP Code 95064 (Intensity IV, 3 responses)" insttype="USGS (Did You Feel It?)" lat="37.000057" lon="-122.062214" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="4.0">
<comp name="Intensity Questionnaire">
<acc value="3.5874" />
<vel value="2.9889" />
</comp>
</station>
<station code="90038" name="ZIP Code 90038 (Intensity VIII, 8 responses)" insttype="USGS (Did You Feel It?)" lat="34.088973" lon="-118.32666" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.9">
<comp name="Intensity Questionnaire">
<acc value="41.7208" />
<vel value="39.7579" />
</comp>
</station>
<station code="89120" name="ZIP Code 89120 (Intensity IV, 3 responses)" insttype="USGS (Did You Feel It?)" lat="36.081493" lon="-115.095768" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="3.9">
<comp name="Intensity Questionnaire">
<acc value="3.3687" />
<vel value="2.7970" />
</comp>
</station>
<station code="90806" name="ZIP Code 90806 (Intensity VII, 6 responses)" insttype="USGS (Did You Feel It?)" lat="33.804549" lon="-118.193697" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.1">
<comp name="Intensity Questionnaire">
<acc value="25.2217" />
<vel value="23.3817" />
</comp>
</station>
<station code="90621" name="ZIP Code 90621 (Intensity VI, 12 responses)" insttype="USGS (Did You Feel It?)" lat="33.874951" lon="-117.99325" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.3">
<comp name="Intensity Questionnaire">
<acc value="15.2474" />
<vel value="13.7508" />
</comp>
</station>
<station code="92262" name="ZIP Code 92262 (Intensity V, 10 responses)" insttype="USGS (Did You Feel It?)" lat="33.862530" lon="-116.568348" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.0">
<comp name="Intensity Questionnaire">
<acc value="6.7298" />
<vel value="5.8035" />
</comp>
</station>
<station code="91801" name="ZIP Code 91801 (Intensity VII, 13 responses)" insttype="USGS (Did You Feel It?)" lat="34.090557" lon="-118.128163" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.9">
<comp name="Intensity Questionnaire">
<acc value="22.2397" />
<vel value="20.4757" />
</comp>
</station>
<station code="92220" name="ZIP Code 92220 (Intensity IV, 4 responses)" insttype="USGS (Did You Feel It?)" lat="33.941408" lon="-116.85235" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="4.2">
<comp name="Intensity Questionnaire">
<acc value="4.0684" />
<vel value="3.4130" />
</comp>
</station>
<station code="93405" name="ZIP Code 93405 (Intensity V, 5 responses)" insttype="USGS (Did You Feel It?)" lat="35.278444" lon="-120.781032" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.0">
<comp name="Intensity Questionnaire">
<acc value="6.7298" />
<vel value="5.8035" />
</comp>
</station>
<station code="93108" name="ZIP Code 93108 (Intensity V, 10 responses)" insttype="USGS (Did You Feel It?)" lat="34.453860" lon="-119.544237" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.2">
<comp name="Intensity Questionnaire">
<acc value="7.6322" />
<vel value="6.6271" />
</comp>
</station>
<station code="93304" name="ZIP Code 93304 (Intensity IV, 16 responses)" insttype="USGS (Did You Feel It?)" lat="35.339342" lon="-119.023666" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="4.4">
<comp name="Intensity Questionnaire">
<acc value="4.6139" />
<vel value="3.8974" />
</comp>
</station>
<station code="92567" name="ZIP Code 92567 (Intensity VI, 4 responses)" insttype="USGS (Did You Feel It?)" lat="33.810151" lon="-117.100581" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.8">
<comp name="Intensity Questionnaire">
<acc value="11.1322" />
<vel value="9.8682" />
</comp>
</station>
<station code="91006" name="ZIP Code 91006 (Intensity VI, 21 responses)" insttype="USGS (Did You Feel It?)" lat="34.135879" lon="-118.02738" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.4">
<comp name="Intensity Questionnaire">
<acc value="16.2374" />
<vel value="14.6942" />
</comp>
</station>
<station code="91792" name="ZIP Code 91792 (Intensity VI, 3 responses)" insttype="USGS (Did You Feel It?)" lat="34.025495" lon="-117.900062" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.2">
<comp name="Intensity Questionnaire">
<acc value="14.3177" />
<vel value="12.8680" />
</comp>
</station>
<station code="92405" name="ZIP Code 92405 (Intensity VI, 6 responses)" insttype="USGS (Did You Feel It?)" lat="34.146147" lon="-117.304" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.9">
<comp name="Intensity Questionnaire">
<acc value="11.8551" />
<vel value="10.5452" />
</comp>
</station>
<station code="90740" name="ZIP Code 90740 (Intensity VI, 15 responses)" insttype="USGS (Did You Feel It?)" lat="33.754539" lon="-118.07127" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.2">
<comp name="Intensity Questionnaire">
<acc value="14.3177" />
<vel value="12.8680" />
</comp>
</station>
<station code="90045" name="ZIP Code 90045 (Intensity VII, 48 responses)" insttype="USGS (Did You Feel It?)" lat="33.953047" lon="-118.401481" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.6">
<comp name="Intensity Questionnaire">
<acc value="18.4146" />
<vel value="16.7797" />
</comp>
</station>
<station code="93243" name="ZIP Code 93243 (Intensity V, 6 responses)" insttype="USGS (Did You Feel It?)" lat="34.706614" lon="-118.885192" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.4">
<comp name="Intensity Questionnaire">
<acc value="8.6555" />
<vel value="7.5677" />
</comp>
</station>
<station code="92307" name="ZIP Code 92307 (Intensity V, 9 responses)" insttype="USGS (Did You Feel It?)" lat="34.592432" lon="-117.131185" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.1">
<comp name="Intensity Questionnaire">
<acc value="7.1668" />
<vel value="6.2016" />
</comp>
</station>
<station code="91345" name="ZIP Code 91345 (Intensity IX, 19 responses)" insttype="USGS (Did You Feel It?)" lat="34.266453" lon="-118.460354" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="8.6">
<comp name="Intensity Questionnaire">
<acc value="64.8052" />
<vel value="63.2634" />
</comp>
</station>
<station code="93063" name="ZIP Code 93063 (Intensity IX, 143 responses)" insttype="USGS (Did You Feel It?)" lat="34.288237" lon="-118.688935" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="8.6">
<comp name="Intensity Questionnaire">
<acc value="64.8052" />
<vel value="63.2634" />
</comp>
</station>
<station code="91745" name="ZIP Code 91745 (Intensity VI, 25 responses)" insttype="USGS (Did You Feel It?)" lat="34.000621" lon="-117.975849" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.2">
<comp name="Intensity Questionnaire">
<acc value="14.3177" />
<vel value="12.8680" />
</comp>
</station>
<station code="92604" name="ZIP Code 92604 (Intensity V, 17 responses)" insttype="USGS (Did You Feel It?)" lat="33.688102" lon="-117.788567" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.3">
<comp name="Intensity Questionnaire">
<acc value="8.1278" />
<vel value="7.0818" />
</comp>
</station>
<station code="90814" name="ZIP Code 90814 (Intensity VI, 20 responses)" insttype="USGS (Did You Feel It?)" lat="33.771699" lon="-118.144049" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.1">
<comp name="Intensity Questionnaire">
<acc value="13.4447" />
<vel value="12.0418" />
</comp>
</station>
<station code="92861" name="ZIP Code 92861 (Intensity VI, 3 responses)" insttype="USGS (Did You Feel It?)" lat="33.817341" lon="-117.810148" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.5">
<comp name="Intensity Questionnaire">
<acc value="9.2175" />
<vel value="8.0869" />
</comp>
</station>
<station code="92130" name="ZIP Code 92130 (Intensity V, 6 responses)" insttype="USGS (Did You Feel It?)" lat="32.953944" lon="-117.201406" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.0">
<comp name="Intensity Questionnaire">
<acc value="6.7298" />
<vel value="5.8035" />
</comp>
</station>
<station code="92571" name="ZIP Code 92571 (Intensity VI, 5 responses)" insttype="USGS (Did You Feel It?)" lat="33.834610" lon="-117.18995" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.5">
<comp name="Intensity Questionnaire">
<acc value="9.2175" />
<vel value="8.0869" />
</comp>
</station>
<station code="91340" name="ZIP Code 91340 (Intensity VIII, 6 responses)" insttype="USGS (Did You Feel It?)" lat="34.287043" lon="-118.434841" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="8.3">
<comp name="Intensity Questionnaire">
<acc value="53.6590" />
<vel value="51.8439" />
</comp>
</station>
<station code="90031" name="ZIP Code 90031 (Intensity VII, 9 responses)" insttype="USGS (Did You Feel It?)" lat="34.079627" lon="-118.211363" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.2">
<comp name="Intensity Questionnaire">
<acc value="26.8594" />
<vel value="24.9859" />
</comp>
</station>
<station code="93534" name="ZIP Code 93534 (Intensity VI, 32 responses)" insttype="USGS (Did You Feel It?)" lat="34.720258" lon="-118.148503" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.7">
<comp name="Intensity Questionnaire">
<acc value="10.4535" />
<vel value="9.2346" />
</comp>
</station>
<station code="91301" name="ZIP Code 91301 (Intensity VII, 53 responses)" insttype="USGS (Did You Feel It?)" lat="34.136492" lon="-118.756362" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.4">
<comp name="Intensity Questionnaire">
<acc value="30.4608" />
<vel value="28.5319" />
</comp>
</station>
<station code="91762" name="ZIP Code 91762 (Intensity VI, 9 responses)" insttype="USGS (Did You Feel It?)" lat="34.056865" lon="-117.667627" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.7">
<comp name="Intensity Questionnaire">
<acc value="10.4535" />
<vel value="9.2346" />
</comp>
</station>
<station code="93268" name="ZIP Code 93268 (Intensity V, 4 responses)" insttype="USGS (Did You Feel It?)" lat="35.169943" lon="-119.424332" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="4.7">
<comp name="Intensity Questionnaire">
<acc value="5.5723" />
<vel value="4.7559" />
</comp>
</station>
<station code="92123" name="ZIP Code 92123 (Intensity V, 8 responses)" insttype="USGS (Did You Feel It?)" lat="32.805908" lon="-117.135159" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.0">
<comp name="Intensity Questionnaire">
<acc value="6.7298" />
<vel value="5.8035" />
</comp>
</station>
<station code="91776" name="ZIP Code 91776 (Intensity VII, 13 responses)" insttype="USGS (Did You Feel It?)" lat="34.089723" lon="-118.095535" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.6">
<comp name="Intensity Questionnaire">
<acc value="18.4146" />
<vel value="16.7797" />
</comp>
</station>
<station code="93012" name="ZIP Code 93012 (Intensity VII, 48 responses)" insttype="USGS (Did You Feel It?)" lat="34.205749" lon="-118.992762" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.9">
<comp name="Intensity Questionnaire">
<acc value="22.2397" />
<vel value="20.4757" />
</comp>
</station>
<station code="93110" name="ZIP Code 93110 (Intensity VI, 15 responses)" insttype="USGS (Did You Feel It?)" lat="34.435052" lon="-119.768968" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.5">
<comp name="Intensity Questionnaire">
<acc value="9.2175" />
<vel value="8.0869" />
</comp>
</station>
<station code="93444" name="ZIP Code 93444 (Intensity V, 4 responses)" insttype="USGS (Did You Feel It?)" lat="35.027647" lon="-120.49714" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="4.8">
<comp name="Intensity Questionnaire">
<acc value="5.9341" />
<vel value="5.0822" />
</comp>
</station>
<station code="92240" name="ZIP Code 92240 (Intensity IV, 4 responses)" insttype="USGS (Did You Feel It?)" lat="33.962758" lon="-116.529621" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="3.6">
<comp name="Intensity Questionnaire">
<acc value="2.7893" />
<vel value="2.2921" />
</comp>
</station>
<station code="89109" name="ZIP Code 89109 (Intensity IV, 12 responses)" insttype="USGS (Did You Feel It?)" lat="36.125968" lon="-115.153324" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="3.9">
<comp name="Intensity Questionnaire">
<acc value="3.3687" />
<vel value="2.7970" />
</comp>
</station>
<station code="91780" name="ZIP Code 91780 (Intensity VI, 13 responses)" insttype="USGS (Did You Feel It?)" lat="34.101689" lon="-118.055676" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.4">
<comp name="Intensity Questionnaire">
<acc value="16.2374" />
<vel value="14.6942" />
</comp>
</station>
<station code="90670" name="ZIP Code 90670 (Intensity VII, 5 responses)" insttype="USGS (Did You Feel It?)" lat="33.932182" lon="-118.062376" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.7">
<comp name="Intensity Questionnaire">
<acc value="19.6103" />
<vel value="17.9309" />
</comp>
</station>
<station code="90011" name="ZIP Code 90011 (Intensity VIII, 6 responses)" insttype="USGS (Did You Feel It?)" lat="34.007530" lon="-118.258744" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.7">
<comp name="Intensity Questionnaire">
<acc value="36.7882" />
<vel value="34.8166" />
</comp>
</station>
<station code="92555" name="ZIP Code 92555 (Intensity V, 5 responses)" insttype="USGS (Did You Feel It?)" lat="33.905446" lon="-117.125722" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.1">
<comp name="Intensity Questionnaire">
<acc value="7.1668" />
<vel value="6.2016" />
</comp>
</station>
<station code="91505" name="ZIP Code 91505 (Intensity VIII, 54 responses)" insttype="USGS (Did You Feel It?)" lat="34.177031" lon="-118.347892" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.9">
<comp name="Intensity Questionnaire">
<acc value="41.7208" />
<vel value="39.7579" />
</comp>
</station>
<station code="92782" name="ZIP Code 92782 (Intensity VI, 6 responses)" insttype="USGS (Did You Feel It?)" lat="33.726158" lon="-117.800197" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.4">
<comp name="Intensity Questionnaire">
<acc value="16.2374" />
<vel value="14.6942" />
</comp>
</station>
<station code="92397" name="ZIP Code 92397 (Intensity VI, 9 responses)" insttype="USGS (Did You Feel It?)" lat="34.348403" lon="-117.587544" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.5">
<comp name="Intensity Questionnaire">
<acc value="9.2175" />
<vel value="8.0869" />
</comp>
</station>
<station code="91361" name="ZIP Code 91361 (Intensity VII, 26 responses)" insttype="USGS (Did You Feel It?)" lat="34.146009" lon="-118.878224" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="7.1">
<comp name="Intensity Questionnaire">
<acc value="25.2217" />
<vel value="23.3817" />
</comp>
</station>
<station code="90028" name="ZIP Code 90028 (Intensity VIII, 25 responses)" insttype="USGS (Did You Feel It?)" lat="34.099780" lon="-118.32672" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="8.0">
<comp name="Intensity Questionnaire">
<acc value="44.4299" />
<vel value="42.4856" />
</comp>
</station>
<station code="91709" name="ZIP Code 91709 (Intensity VI, 23 responses)" insttype="USGS (Did You Feel It?)" lat="33.950662" lon="-117.725696" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.1">
<comp name="Intensity Questionnaire">
<acc value="13.4447" />
<vel value="12.0418" />
</comp>
</station>
<station code="91011" name="ZIP Code 91011 (Intensity VII, 22 responses)" insttype="USGS (Did You Feel It?)" lat="34.224757" lon="-118.111466" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="6.5">
<comp name="Intensity Questionnaire">
<acc value="17.2918" />
<vel value="15.7024" />
</comp>
</station>
<station code="92530" name="ZIP Code 92530 (Intensity VI, 12 responses)" insttype="USGS (Did You Feel It?)" lat="33.607297" lon="-117.395824" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.8">
<comp name="Intensity Questionnaire">
<acc value="11.1322" />
<vel value="9.8682" />
</comp>
</station>
<station code="91932" name="ZIP Code 91932 (Intensity V, 3 responses)" insttype="USGS (Did You Feel It?)" lat="32.579303" lon="-117.117645" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="5.2">
<comp name="Intensity Questionnaire">
<acc value="7.6322" />